### POST /api/v1/config/test
POST http://localhost:3000/api/v1/config/wishlistwrangler
Content-Type: application/json
Authorization: Bearer {{wishlistwranglerToken}}

{
    "name": "test",
    "value": "test"
}

### GET /api/v1/config/test
GET http://localhost:3000/api/v1/config/test
Content-Type: application/json
Authorization: Bearer {{wishlistwranglerToken}}

### Post activate config
POST http://localhost:3000/api/v1/config/test1/activate/4
Content-Type: application/json
Authorization: Bearer {{wishlistwranglerToken}}
