### POST /api/v1/config/test
POST http://localhost:3000/api/v1/config/test
Content-Type: application/json

{
    "name": "test",
    "value": "test"
}

### GET /api/v1/config/test
GET http://localhost:3000/api/v1/config/test
Content-Type: application/json

### Post activate config
POST http://localhost:3000/api/v1/config/test/activate/3
Content-Type: application/json
