// Code generated by ent, DO NOT EDIT.

package ent

import (
	"RjsConfigService/ent/appconfig"
	"RjsConfigService/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AppConfigUpdate is the builder for updating AppConfig entities.
type AppConfigUpdate struct {
	config
	hooks    []Hook
	mutation *AppConfigMutation
}

// Where appends a list predicates to the AppConfigUpdate builder.
func (acu *AppConfigUpdate) Where(ps ...predicate.AppConfig) *AppConfigUpdate {
	acu.mutation.Where(ps...)
	return acu
}

// SetCreatedAt sets the "created_at" field.
func (acu *AppConfigUpdate) SetCreatedAt(t time.Time) *AppConfigUpdate {
	acu.mutation.SetCreatedAt(t)
	return acu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (acu *AppConfigUpdate) SetNillableCreatedAt(t *time.Time) *AppConfigUpdate {
	if t != nil {
		acu.SetCreatedAt(*t)
	}
	return acu
}

// SetAppName sets the "app_name" field.
func (acu *AppConfigUpdate) SetAppName(s string) *AppConfigUpdate {
	acu.mutation.SetAppName(s)
	return acu
}

// SetNillableAppName sets the "app_name" field if the given value is not nil.
func (acu *AppConfigUpdate) SetNillableAppName(s *string) *AppConfigUpdate {
	if s != nil {
		acu.SetAppName(*s)
	}
	return acu
}

// SetVersion sets the "version" field.
func (acu *AppConfigUpdate) SetVersion(i int) *AppConfigUpdate {
	acu.mutation.ResetVersion()
	acu.mutation.SetVersion(i)
	return acu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (acu *AppConfigUpdate) SetNillableVersion(i *int) *AppConfigUpdate {
	if i != nil {
		acu.SetVersion(*i)
	}
	return acu
}

// AddVersion adds i to the "version" field.
func (acu *AppConfigUpdate) AddVersion(i int) *AppConfigUpdate {
	acu.mutation.AddVersion(i)
	return acu
}

// SetStatus sets the "status" field.
func (acu *AppConfigUpdate) SetStatus(a appconfig.Status) *AppConfigUpdate {
	acu.mutation.SetStatus(a)
	return acu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (acu *AppConfigUpdate) SetNillableStatus(a *appconfig.Status) *AppConfigUpdate {
	if a != nil {
		acu.SetStatus(*a)
	}
	return acu
}

// SetConfig sets the "config" field.
func (acu *AppConfigUpdate) SetConfig(m map[string]interface{}) *AppConfigUpdate {
	acu.mutation.SetConfig(m)
	return acu
}

// Mutation returns the AppConfigMutation object of the builder.
func (acu *AppConfigUpdate) Mutation() *AppConfigMutation {
	return acu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (acu *AppConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, acu.sqlSave, acu.mutation, acu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (acu *AppConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := acu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (acu *AppConfigUpdate) Exec(ctx context.Context) error {
	_, err := acu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acu *AppConfigUpdate) ExecX(ctx context.Context) {
	if err := acu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (acu *AppConfigUpdate) check() error {
	if v, ok := acu.mutation.Status(); ok {
		if err := appconfig.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AppConfig.status": %w`, err)}
		}
	}
	return nil
}

func (acu *AppConfigUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := acu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(appconfig.Table, appconfig.Columns, sqlgraph.NewFieldSpec(appconfig.FieldID, field.TypeUUID))
	if ps := acu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := acu.mutation.CreatedAt(); ok {
		_spec.SetField(appconfig.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := acu.mutation.AppName(); ok {
		_spec.SetField(appconfig.FieldAppName, field.TypeString, value)
	}
	if value, ok := acu.mutation.Version(); ok {
		_spec.SetField(appconfig.FieldVersion, field.TypeInt, value)
	}
	if value, ok := acu.mutation.AddedVersion(); ok {
		_spec.AddField(appconfig.FieldVersion, field.TypeInt, value)
	}
	if value, ok := acu.mutation.Status(); ok {
		_spec.SetField(appconfig.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := acu.mutation.Config(); ok {
		_spec.SetField(appconfig.FieldConfig, field.TypeJSON, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, acu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	acu.mutation.done = true
	return n, nil
}

// AppConfigUpdateOne is the builder for updating a single AppConfig entity.
type AppConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppConfigMutation
}

// SetCreatedAt sets the "created_at" field.
func (acuo *AppConfigUpdateOne) SetCreatedAt(t time.Time) *AppConfigUpdateOne {
	acuo.mutation.SetCreatedAt(t)
	return acuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (acuo *AppConfigUpdateOne) SetNillableCreatedAt(t *time.Time) *AppConfigUpdateOne {
	if t != nil {
		acuo.SetCreatedAt(*t)
	}
	return acuo
}

// SetAppName sets the "app_name" field.
func (acuo *AppConfigUpdateOne) SetAppName(s string) *AppConfigUpdateOne {
	acuo.mutation.SetAppName(s)
	return acuo
}

// SetNillableAppName sets the "app_name" field if the given value is not nil.
func (acuo *AppConfigUpdateOne) SetNillableAppName(s *string) *AppConfigUpdateOne {
	if s != nil {
		acuo.SetAppName(*s)
	}
	return acuo
}

// SetVersion sets the "version" field.
func (acuo *AppConfigUpdateOne) SetVersion(i int) *AppConfigUpdateOne {
	acuo.mutation.ResetVersion()
	acuo.mutation.SetVersion(i)
	return acuo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (acuo *AppConfigUpdateOne) SetNillableVersion(i *int) *AppConfigUpdateOne {
	if i != nil {
		acuo.SetVersion(*i)
	}
	return acuo
}

// AddVersion adds i to the "version" field.
func (acuo *AppConfigUpdateOne) AddVersion(i int) *AppConfigUpdateOne {
	acuo.mutation.AddVersion(i)
	return acuo
}

// SetStatus sets the "status" field.
func (acuo *AppConfigUpdateOne) SetStatus(a appconfig.Status) *AppConfigUpdateOne {
	acuo.mutation.SetStatus(a)
	return acuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (acuo *AppConfigUpdateOne) SetNillableStatus(a *appconfig.Status) *AppConfigUpdateOne {
	if a != nil {
		acuo.SetStatus(*a)
	}
	return acuo
}

// SetConfig sets the "config" field.
func (acuo *AppConfigUpdateOne) SetConfig(m map[string]interface{}) *AppConfigUpdateOne {
	acuo.mutation.SetConfig(m)
	return acuo
}

// Mutation returns the AppConfigMutation object of the builder.
func (acuo *AppConfigUpdateOne) Mutation() *AppConfigMutation {
	return acuo.mutation
}

// Where appends a list predicates to the AppConfigUpdate builder.
func (acuo *AppConfigUpdateOne) Where(ps ...predicate.AppConfig) *AppConfigUpdateOne {
	acuo.mutation.Where(ps...)
	return acuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (acuo *AppConfigUpdateOne) Select(field string, fields ...string) *AppConfigUpdateOne {
	acuo.fields = append([]string{field}, fields...)
	return acuo
}

// Save executes the query and returns the updated AppConfig entity.
func (acuo *AppConfigUpdateOne) Save(ctx context.Context) (*AppConfig, error) {
	return withHooks(ctx, acuo.sqlSave, acuo.mutation, acuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (acuo *AppConfigUpdateOne) SaveX(ctx context.Context) *AppConfig {
	node, err := acuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (acuo *AppConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := acuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acuo *AppConfigUpdateOne) ExecX(ctx context.Context) {
	if err := acuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (acuo *AppConfigUpdateOne) check() error {
	if v, ok := acuo.mutation.Status(); ok {
		if err := appconfig.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AppConfig.status": %w`, err)}
		}
	}
	return nil
}

func (acuo *AppConfigUpdateOne) sqlSave(ctx context.Context) (_node *AppConfig, err error) {
	if err := acuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(appconfig.Table, appconfig.Columns, sqlgraph.NewFieldSpec(appconfig.FieldID, field.TypeUUID))
	id, ok := acuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := acuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appconfig.FieldID)
		for _, f := range fields {
			if !appconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := acuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := acuo.mutation.CreatedAt(); ok {
		_spec.SetField(appconfig.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := acuo.mutation.AppName(); ok {
		_spec.SetField(appconfig.FieldAppName, field.TypeString, value)
	}
	if value, ok := acuo.mutation.Version(); ok {
		_spec.SetField(appconfig.FieldVersion, field.TypeInt, value)
	}
	if value, ok := acuo.mutation.AddedVersion(); ok {
		_spec.AddField(appconfig.FieldVersion, field.TypeInt, value)
	}
	if value, ok := acuo.mutation.Status(); ok {
		_spec.SetField(appconfig.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := acuo.mutation.Config(); ok {
		_spec.SetField(appconfig.FieldConfig, field.TypeJSON, value)
	}
	_node = &AppConfig{config: acuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, acuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	acuo.mutation.done = true
	return _node, nil
}
