// Code generated by ent, DO NOT EDIT.

package ent

import (
	"config-service/ent/appconfig"
	"config-service/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AppConfigUpdate is the builder for updating AppConfig entities.
type AppConfigUpdate struct {
	config
	hooks    []Hook
	mutation *AppConfigMutation
}

// Where appends a list predicates to the AppConfigUpdate builder.
func (_u *AppConfigUpdate) Where(ps ...predicate.AppConfig) *AppConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AppConfigUpdate) SetCreatedAt(v time.Time) *AppConfigUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillableCreatedAt(v *time.Time) *AppConfigUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetAppName sets the "app_name" field.
func (_u *AppConfigUpdate) SetAppName(v string) *AppConfigUpdate {
	_u.mutation.SetAppName(v)
	return _u
}

// SetNillableAppName sets the "app_name" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillableAppName(v *string) *AppConfigUpdate {
	if v != nil {
		_u.SetAppName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *AppConfigUpdate) SetVersion(v int) *AppConfigUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillableVersion(v *int) *AppConfigUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *AppConfigUpdate) AddVersion(v int) *AppConfigUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AppConfigUpdate) SetStatus(v string) *AppConfigUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillableStatus(v *string) *AppConfigUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *AppConfigUpdate) SetConfig(v map[string]interface{}) *AppConfigUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// Mutation returns the AppConfigMutation object of the builder.
func (_u *AppConfigUpdate) Mutation() *AppConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AppConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AppConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AppConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(appconfig.Table, appconfig.Columns, sqlgraph.NewFieldSpec(appconfig.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(appconfig.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AppName(); ok {
		_spec.SetField(appconfig.FieldAppName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(appconfig.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(appconfig.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(appconfig.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(appconfig.FieldConfig, field.TypeJSON, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AppConfigUpdateOne is the builder for updating a single AppConfig entity.
type AppConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppConfigMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *AppConfigUpdateOne) SetCreatedAt(v time.Time) *AppConfigUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillableCreatedAt(v *time.Time) *AppConfigUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetAppName sets the "app_name" field.
func (_u *AppConfigUpdateOne) SetAppName(v string) *AppConfigUpdateOne {
	_u.mutation.SetAppName(v)
	return _u
}

// SetNillableAppName sets the "app_name" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillableAppName(v *string) *AppConfigUpdateOne {
	if v != nil {
		_u.SetAppName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *AppConfigUpdateOne) SetVersion(v int) *AppConfigUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillableVersion(v *int) *AppConfigUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *AppConfigUpdateOne) AddVersion(v int) *AppConfigUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AppConfigUpdateOne) SetStatus(v string) *AppConfigUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillableStatus(v *string) *AppConfigUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *AppConfigUpdateOne) SetConfig(v map[string]interface{}) *AppConfigUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// Mutation returns the AppConfigMutation object of the builder.
func (_u *AppConfigUpdateOne) Mutation() *AppConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the AppConfigUpdate builder.
func (_u *AppConfigUpdateOne) Where(ps ...predicate.AppConfig) *AppConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AppConfigUpdateOne) Select(field string, fields ...string) *AppConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AppConfig entity.
func (_u *AppConfigUpdateOne) Save(ctx context.Context) (*AppConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppConfigUpdateOne) SaveX(ctx context.Context) *AppConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AppConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AppConfigUpdateOne) sqlSave(ctx context.Context) (_node *AppConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(appconfig.Table, appconfig.Columns, sqlgraph.NewFieldSpec(appconfig.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appconfig.FieldID)
		for _, f := range fields {
			if !appconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(appconfig.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AppName(); ok {
		_spec.SetField(appconfig.FieldAppName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(appconfig.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(appconfig.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(appconfig.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(appconfig.FieldConfig, field.TypeJSON, value)
	}
	_node = &AppConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
